name: Deploy Spring Boot (Gradle) to Azure App Service

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: backend   # gradlew가 backend 폴더 안에 있을 경우

      - name: Build with Gradle (skip tests)
        run: ./gradlew clean bootJar -x test
        working-directory: backend   # backend 폴더에서 빌드

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: gnu-game-pot   # 예: gnu-game-pot
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: backend/build/libs/*.jar
