name: Deploy Spring Boot (Gradle) to Azure App Service

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: backend

      - name: Build with Gradle (skip tests)
        run: ./gradlew clean bootJar -x test
        working-directory: backend

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: gamepot
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          # JAR 파일 경로를 직접 지정합니다.
          # 이 파일이 wwwroot의 최상위에 배포됩니다.
          package: backend/build/libs/*.jar

          clean: true
